Update overlap.py to fix_factorial2
theochem/iodata pull request #309
Opened 2024-03-07 10:10 UTC by LudoRNLT

![Capture d'écran 2024-03-07 104652](https://github.com/theochem/iodata/assets/102245368/f07e2777-2cd3-43ec-b1c2-16775d5b97c0)
![Capture d'écran 2024-03-07 104853](https://github.com/theochem/iodata/assets/102245368/d3c3c421-fa65-4142-84eb-469ea375c6c8)

@D-TheProgrammer and I, think that we solved the factorial error. Let us know if we have to do this but in a different way or use another syntax.

2024-03-08 19:30 UTC, PaulWAyers approved these changes
This looks good to me. I've tagged @FarnazH as she did more work on this, so I'd wait a couple days for her to glance at it before merging.

2024-04-03 10:08 UTC, D-TheProgrammer commented
Hi @PaulWAyers  and @FarnazH , @LudoRNLT and I wanted to know if you have any updates regarding our fix and if it still suits you for the merge.

2024-04-03 13:41 UTC, PaulWAyers commented
I think @FarnazH is busy. Perhaps @tovrstra or @marco-2023 has time to do a quick review.

2024-05-03 06:01 UTC, tovrstra commented
@D-TheProgrammer: can you explain the error you were getting and that was fixed with this change? I just ran all unit tests without this change, and they pass (except for the problem fixed in #310).

2024-05-03 06:02 UTC, tovrstra commented on iodata/overlap.py
> +        if n is not int:
Please fix the type checking:
```suggestion
        if not isinstance(n, int):
```

2024-05-03 06:04 UTC, tovrstra commented on iodata/overlap.py
> +                out = scipy.special.factorial2(x, exact) #compute on each individual element x of the array n
Shouldn't this loop be dedented by four spaces?

2024-05-03 06:04 UTC, tovrstra commented on iodata/overlap.py
> +    if exact == False : #Keep when exact=False
```suggestion
    if not exact:
```

2024-05-03 07:07 UTC, tovrstra requested changes
I'm sorry for my initial confusion. I'd like to request a few improvements:

- Major: Please add unit tests for the cases you're fixing. The issue reported in #308 is not covered by our unit tests at the moment. Unit tests for the following cases (once with `exact=True` and once with `exact=False`) would be useful:
    - integer arguments `0`, `1`, `2` and `3`
    - float arguments `0.0`, `1.0`, `2.0` and `3.0`
    - integer array argument `np.array([0, 1, 2, 3])`
    - float array argument `np.array([0.0, 1.0, 2.0, 3.0])`
- Minor: Please avoid comments at the end of a line. Put them on the line before instead. Also, don't add comments with little added value, such as translating a line of Python to a human-readable sentence. Comments are more useful when they explain the intent of the code, typically of a block consisting of multiple lines, which is different from a literal human translation of the code.

Thanks!

2024-06-01 17:54 UTC, tovrstra commented
I'm closing this one because a more recent pull request was made: #319

2024-06-01 17:54 UTC, closed without merging